# tests/test_schemas.py
import pytest
from pydantic import ValidationError
from schemas.input_schema import AgentInput


def test_valid_input_csv():
    inp = AgentInput(
        dataset_path="data/test.csv",
        target_column="label",
        business_problem="Test problem"
    )
    assert inp.task_type == "auto"
    assert inp.max_models == 5


def test_valid_input_excel():
    inp = AgentInput(
        dataset_path="data/test.xlsx",
        target_column="default",
        business_problem="Predict loan defaults"
    )
    assert inp.dataset_path == "data/test.xlsx"


def test_invalid_file_format():
    with pytest.raises(ValidationError):
        AgentInput(
            dataset_path="data/test.pdf",
            target_column="label",
            business_problem="Test"
        )


def test_empty_target_column():
    with pytest.raises(ValidationError):
        AgentInput(
            dataset_path="data/test.csv",
            target_column="   ",
            business_problem="Test"
        )


def test_run_id_autogenerated():
    inp = AgentInput(
        dataset_path="data/test.csv",
        target_column="label",
        business_problem="Test"
    )
    assert inp.run_id.startswith("run_")


def test_extra_context_optional():
    inp = AgentInput(
        dataset_path="data/test.csv",
        target_column="label",
        business_problem="Test",
        extra_context={"domain": "healthcare", "priority_metric": "recall"}
    )
    assert inp.extra_context["domain"] == "healthcare"